### PR TITLE
Remove GitAsyncTask and replace with non-blocking coroutines

### LINKED ISSUE #160: Handle the blocking actions in another thread
Most of the time, the user has to wait until we finish encrypting the password file, committing, pulling or pushing to the repository. All these actions should be done without blocking the UI, once they are done we can show a toast to the user. Todo:
- [ ] Encrypt the password after creation
- [ ] git-commit the add/remove actions
- [ ] git-push and git-pull

### LINKED ISSUE #219: Provide contextual error messages, not “Internal exception occurred”
In many failure scenarios (e.g. issue #153, issue #162, and others) the app presents a raw message from the jgit library.

The jgit library messages are very low-level, and the message presented to the user is lacking important context from the Password Store app about _what it was doing_ when the jgit library raised an exception.

Please catch jgit library exceptions, at each point where useful contextual information from Password Store can be presented in a more useful diagnostic error message.

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description
Refactors the git command execution to be less obtrusive to the users, offer better error messages and use coroutines in place of the aging AsyncTask.

## :bulb: Motivation and Context
`GitAsyncTask` is next on our list of ugly monoliths that need to go. Like GitActivity and PgpActivity, it encapsulates a bit too much logic that is better suited in different places of our execution flow.

## :green_heart: How did you test it?
Completely untested, might not even compile.

## :pencil: Checklist

- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [ ] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
moar coroutines!

### CODE REVIEW

**Comment by msfjarvis** [comment]
@FabianHenneke any particular reason for AutofillSaveActivity not extending AppCompatActivity? Would be 
a bit easier to make things suspend if I don't have to wire up `lifecycleScope` myself :grimacing:

**Comment by FabianHenneke** [comment]
> @FabianHenneke any particular reason for AutofillSaveActivity not extending AppCompatActivity? Would be 
> a bit easier to make things suspend if I don't have to wire up `lifecycleScope` myself :grimacing: 

I don't think there was, please go ahead and change it.

**Comment by msfjarvis** [comment]
> > @FabianHenneke any particular reason for AutofillSaveActivity not extending AppCompatActivity? Would be
> > a bit easier to make things suspend if I don't have to wire up `lifecycleScope` myself grimacing
> 
> I don't think there was, please go ahead and change it.

Cool, thanks for quick response! Now get back on with your weekend :P

**Comment by msfjarvis** [comment]
It seems I broke Android with my extreme refactoring prowess... https://bin.msfjarvis.dev/~5eee41b25d7115001813f9b5

**Comment by msfjarvis** [comment]
Seems like I ran into a bug: https://github.com/Kotlin/kotlinx.coroutines/issues/2041. 1.4-M2 seems to fix it, trying that out.

**Comment by msfjarvis** [comment]
Alright that fixed the crash and everything's broken in the correct ways now. Will come back to this when I need to mellow out.

**Comment by msfjarvis** [comment]
@FabianHenneke how do we feel about eradicating `PasswordFragment` and merging it into `PasswordStore`

**Comment by FabianHenneke** [comment]
> @FabianHenneke how do we feel about eradicating `PasswordFragment` and merging it into `PasswordStore`

They are highly coupled anyway and we are not really ever swapping out fragments anyway, so I would say that's fine if it simplifies things elsewhere.

**Comment by msfjarvis** [comment]
> > @FabianHenneke how do we feel about eradicating `PasswordFragment` and merging it into `PasswordStore`
> 
> They are highly coupled anyway and we are not really ever swapping out fragments anyway, so I would say that's fine if it simplifies things elsewhere. 

Hm but we still have the ToCloneOrNot fragment that's shown on first run, might honestly just make better sense to make it a separate activity.

**Comment by msfjarvis** [comment]
Giving up on that effort for the moment, this is gonna entail a larger refactor involving Autofill and SelectFolderFragment as well which is a distraction I do not want right now. Gonne see if `GitOperationActivity` can somehow be remove since it is basically a shell.

**Comment by msfjarvis** [comment]
TODO:

- ~~Add back some semblance of progress UI~~
- ~~Figure out how I broke `CloneOperation`~~
- Find and fix everything else destroyed by me

**Comment by msfjarvis** [comment]
Let's see if we'll able to keep that timeline.

**Comment by msfjarvis** [comment]
The pre-force push version of this branch has been archived at https://github.com/msfjarvis/Android-Password-Store/tree/stash/refactor/unblock-ui for now in case there's something interesting to look at.

**Comment by msfjarvis** [comment]
Think this is about ready now

File: app/src/main/java/com/zeapo/pwdstore/utils/Result.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+package com.zeapo.pwdstore.utils
+
+/**
+ * Emulates the Rust Result enum but without returning a value in the [Ok] case.
+ * https://doc.rust-lang.org/std/result/enum.Result.html
+ */
+sealed class Result {
+
+    object Ok : Result()
```
Comment (Skrilltrax) [inline app/src/main/java/com/zeapo/pwdstore/utils/Result.kt:14]: Add a generic type here so it can also be used when we want to pass the result value back. Also, I would prefer the naming to be Success and Error

File: app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt [hunk 2]
```diff
@@ -98,7 +99,7 @@ fun Context.getEncryptedPrefs(fileName: String): SharedPreferences {
 }
 
 @MainThread
```
Comment (Skrilltrax) [inline app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt]: Annotation should be `@WorkerThread`

File: app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+    )
+
+    override suspend fun execute() {
+        GitCommandExecutor(callingActivity, this).execute()
+    }
+
+    override fun onError(err: Exception) {
+        super.onError(err)
+        val error = ErrorMessages[err]
+        MaterialAlertDialogBuilder(callingActivity)
```
Comment (Skrilltrax) [inline app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt]: Can we return the result to the `callingActivity` and do the UI work there?

File: app/src/main/java/com/zeapo/pwdstore/utils/Result.kt (hunk 1 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/utils/Result.kt:14]: It's gonna complicate the current use case for no reason. We'll do this when we need it.

File: app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt (hunk 2 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt]: Not too sure about that but I'll look into it.

File: app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt (hunk 3 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt]: Probably not since we're already setting a different result in `GitCommandExecutor`.

**Comment by msfjarvis** [comment]
~~`commitChange` seems to be broken, files are being staged but the commit never finishes.~~ Fixed with https://msfjarvis.dev/aps/bbf711824722

File: app/src/main/java/com/zeapo/pwdstore/git/ErrorMessages.kt [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+package com.zeapo.pwdstore.git
+
+import android.os.RemoteException
+import com.zeapo.pwdstore.Application
+import com.zeapo.pwdstore.R
+
+/**
+ * Supertype for all Git-related [Exception]s that can be thrown by [GitCommandExecutor.execute].
+ */
+open class GitException(message: String? = null) : Exception(message)
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/git/ErrorMessages.kt]: Could we make this a sealed class?

File: app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt (hunk 2 above)
Comment (fmeum) [reply app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt]: Ideally this would not need any kind of thread hint, we should just use withcontext whenever context matters.

File: app/src/main/java/com/zeapo/pwdstore/git/ErrorMessages.kt (hunk 4 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/git/ErrorMessages.kt]: Sure thing.

File: app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt [hunk 5]
```diff
@@ -166,7 +165,13 @@ abstract class GitOperation(gitDir: File, internal val callingActivity: AppCompa
                     }
             }
         }
-        d { ErrorMessages[err] }
+        val error = ErrorMessages[err]
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt]: We may want to debug log the original error here.

**Comment by fmeum** [comment]
When I create a new password, the commit seems to be created correctly, but Password Store is finished when the commit is done. Maybe there is an issue related to `finishActivityOnEnd` here?

**Comment by msfjarvis** [comment]
> When I create a new password, the commit seems to be created correctly, but Password Store is finished when the commit is done. Maybe there is an issue related to `finishActivityOnEnd` here?

I'll check after work.

**Comment by msfjarvis** [comment]
> When I create a new password, the commit seems to be created correctly, but Password Store is finished when the commit is done. Maybe there is an issue related to `finishActivityOnEnd` here?

Should be fixed now along with all the other git related tasks.

**Comment by fmeum** [comment]
Will look into it tomorrow morning. Sorry for the late response, I got caught up in the natural follow-up PR that allows us to finally drop Jsch (coming soon).

**Review by fmeum — APPROVED** [review]
Looks good to me and worked in simple use cases, great work! Let's send it off to the snapshot build.
