### PR TITLE
Properly handle files without passwords

### LINKED ISSUE #967: [BUG] OTP entries aren't being treated as OTP passwords
**Describe the bug**
1.10.0 added back OTP (TOTP) entries. I have existing OTP entries (just moved over from iOS where they were working fine with mssun/passforios) but when I look at the entry in APS, I just see `Password: otpauth://totp/[...]`.

**To Reproduce**
1. Open an OTP entry
2. See the standard password view instead of an OTP code

**Expected behavior**

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Stock ROM, Android 10
 - App version 1.10.0

**Additional context**
Does the entry need to be labeled specially? I saw in the code it just looks for [`startsWith("otpauth://totp/")`](https://github.com/android-password-store/Android-Password-Store/blob/c5a93b8b8168eead37f3f93a8e8378211c1d240b/app/src/main/java/com/zeapo/pwdstore/utils/UriTotpFinder.kt#L17) so I don't think there is anything else I need to do.

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
If the first line of the password file contains any of our valid start identifiers for TOTP or username detection, mark
the file as having no password and let it be used as extra content.

## :bulb: Motivation and Context
Fixes #967

## :green_heart: How did you test it?
Added unit and instrumentation tests to verify the behavior

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt [hunk 1]
```diff
@@ -118,5 +120,7 @@ class PasswordEntry(content: String, private val totpFinder: TotpFinder = UriTot
             "id:",
             "identity:"
         )
+
+        private val EXTRA_CONTENT_FIELDS = USERNAME_FIELDS + UriTotpFinder.TOTP_FIELDS
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt]: Imo we should be only looking for either password or TOTP fields specifically in the first line. That's because I don't really see a use case for a username-only entry, but I can definitely see this randomly breaking entries where the password happens to start with `id:`.

Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt]: Hm that does make sense. Will make the change.

**Review by fmeum — APPROVED** [review]
