### PR TITLE
Resolve Autofill breakage below API 30

### LINKED ISSUE #1186: [BUG] Autofill broken below Android 11 due to missing InlinePresentationSpec
```
Process: dev.msfjarvis.aps, PID: 13810
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/widget/inline/InlinePresentationSpec;
        at com.zeapo.pwdstore.autofill.oreo.AutofillResponseBuilder.makeFillResponse(AutofillResponseBuilder.kt:28)
        at com.zeapo.pwdstore.autofill.oreo.OreoAutofillService.onFillRequest(OreoAutofillService.kt:87)
        at android.service.autofill.-$$Lambda$I0gCKFrBTO70VZfSZTq2fj-wyG8.accept(Unknown Source:8)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:300)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.ClassNotFoundException: android.widget.inline.InlinePresentationSpec
        ... 13 more
```

version 2.0.0-SNAPSHOT Free flavor

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Fix Autofill crashing on Android 10 and below by moving Android 11 specific API into a separate, gated class.

## :bulb: Motivation and Context
Broken autofill is a problem when we're shilling it so hard :P
Fixes #1186 

## :green_heart: How did you test it?
Verified I can now fill into sites and apps on Android 10.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+        context: Context,
+        action: AutofillAction,
+        intentSender: IntentSender,
+        metadata: DatasetMetadata,
+        imeSpec: InlinePresentationSpec?,
+    ): Dataset {
+        return Dataset.Builder(makeRemoteView(context, metadata)).run {
+            fillWith(scenario, action, credentials = null)
+            setAuthentication(intentSender)
+            if (imeSpec != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt]: Could we get rid of the checks here now that this is R+ only?

**Review by fmeum — DISMISSED** [review]
I obviously don't like the duplication,but there doesn't seem to be a way around it. Thanks for the quick fix.

File: app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt (hunk 1 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt]: Yep, removed.

**Comment by msfjarvis** [comment]
> I obviously don't like the duplication,but there doesn't seem to be a way around it. Thanks for the quick fix.

Yeah I'm not a fan either but I couldn't find any alternative to this :/

File: app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+        )
+        return makeIntentDataset(context, AutofillAction.Match, intentSender, metadata, imeSpec)
+    }
+
+    private fun makePublisherChangedResponse(
+        context: Context,
+        inlineSuggestionsRequest: InlineSuggestionsRequest?,
+        publisherChangedException: AutofillPublisherChangedException
+    ): FillResponse {
+        val imeSpec = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt]: Sorry, missed one more check.

File: app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+        return FillResponse.Builder().run {
+            addDataset(makePublisherChangedDataset(context, publisherChangedException, imeSpec))
+            setIgnoredIds(*ignoredIds.toTypedArray())
+            build()
+        }
+    }
+
+    private fun makeFillResponse(context: Context, inlineSuggestionsRequest: InlineSuggestionsRequest?, matchedFiles: List<File>): FillResponse? {
+        var datasetCount = 0
+        val imeSpecs: List<InlinePresentationSpec> = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt]: And another one.

File: app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt [hunk 4]
```diff
@@ -0,0 +1,199 @@
...
+            makeGenerateDataset(context, imeSpecs.getOrNull(datasetCount))?.let {
+                datasetCount++
+                addDataset(it)
+            }
+            makeFillOtpFromSmsDataset(context, imeSpecs.getOrNull(datasetCount))?.let {
+                datasetCount++
+                addDataset(it)
+            }
+            if (datasetCount == 0) return null
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
```
Comment (fmeum) [inline app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Api30AutofillResponseBuilder.kt]: This can also go.

**Comment by msfjarvis** [comment]
All done

**Review by fmeum — APPROVED** [review]
