### PR TITLE
Append trailing newline to `.gpg-id` during creation

### LINKED ISSUE #1343: [BUG] .gpg-id created by Android Password Store is rejected by pass v1.7.3
**Describe the bug**
I was experiencing bug #998, and I followed this workaround: https://github.com/android-password-store/Android-Password-Store/issues/1277#issuecomment-759265495.

The new .gpg-id file created by Android Password Store works well for creating new passwords in the app, but not for creating new passwords using pass (v1.7.3) and gnupg2 (v2.2.20) on my laptop.

Pass says:
`gpg: no valid addressees`
`gpg: /dev/shm/pass.wr7YR2EMG5xSx/tf9B1Q-folder-domain.com.txt: encryption failed: No user ID`

I will try to use an email as ID instead, but I wanted to notify you about this.

**To Reproduce**
1. Delete the .gpg-id file from the Password Store repo.
2. Create a new password using the Android Password Store.
3. Sync repo.
4. Create a new password using pass 1.7.3 on a computer.

**Expected behavior**
The GPG key ID written by Android Password Store should be understood by pass on the computer.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - Device: Sony Xperia 10 ii
 - OS: stock ROM Android version 11.0
 - App version: 1.13.3
 - Desktop programs: gnupg2-2.2.20-2.fc32.x86_64, pass-1.7.3-5.fc32.noarch

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Appends an empty string to the key IDs array to ensure a trailing newline is always inserted into the `.gpg-id` file.

## :bulb: Motivation and Context

Fixes #1343

## :green_heart: How did you test it?

Verified I can create passwords on my desktop with a `.gpg-id` file created by APS

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

File: app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt [hunk 1]
```diff
@@ -105,7 +105,7 @@ class PasswordCreationActivity : BasePgpActivity(), OpenPgpServiceConnection.OnB
                 lifecycleScope.launch {
                     val gpgIdentifierFile = File(PasswordRepository.getRepositoryDirectory(), ".gpg-id")
                     withContext(Dispatchers.IO) {
-                        gpgIdentifierFile.writeText(keyIds.joinToString("\n"))
+                        gpgIdentifierFile.writeText((keyIds + "").joinToString("\n"))
```
Comment (fmeum) [inline app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt:108]: The postfix argument may also do the job.

**Review by fmeum — APPROVED** [review]
