### PR TITLE
Disallow overwriting passwords when editing

### LINKED ISSUE #1285: [BUG] Existing files checking issues when renaming a file
**Describe the bug**
When renaming a file, the app doesn't check for existing files as it does when creating a file, therefore may delete a password

**To Reproduce**
1. Create two new password with different names
2. Rename one of them like the other
3. There is only one password

**Expected behavior**
The app should send a toast notification as it does when we try to create a password with an existing name

**Screenshots**
initially

when I rename test2 to test

**Device information (please complete the following information):**
 - Device: Cubot Power
 - OS: Stock ROM Android 8 AOSP
 - App version 1.13.2 FDroid

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Expands the file existence checks when saving to prevent accidentally overwriting other password files.

## :bulb: Motivation and Context
Fixes #1285

## :green_heart: How did you test it?
Tried renaming to an existing password when editing and confirmed that it didn't go through.

## :pencil: Checklist

- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
Split out the creation and editing screens to prevent these bugs.

### CODE REVIEW

File: app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt [hunk 1]
```diff
@@ -398,7 +398,10 @@ class PasswordCreationActivity : BasePgpActivity(), OpenPgpServiceConnection.OnB
                             runCatching {
                                 val file = File(path)
                                 // If we're not editing, this file should not already exist!
-                                if (!editing && file.exists()) {
+                                // Additionally, if we were editing and the incoming and outgoing
+                                // filenames differ, it means we renamed. Ensure that the target
+                                // doesn't already exist to prevent an accidental overwrite.
+                                if ((!editing || editing && suggestedName != file.nameWithoutExtension) && file.exists()) {
```
Comment (Skrilltrax) [inline app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt]:
```suggestion
                                if ((!editing || (editing && suggestedName != file.nameWithoutExtension)) && file.exists()) {
```

I think an extra layer of parenthesis would make it more clear

**Review by Skrilltrax — APPROVED** [review]
