### PR TITLE
Workaround AndroidX lifecycle requirements in OpenKeychain auth

### LINKED ISSUE #1164: OpenKeychain SSH Authentication Mode broken
When using OpenKeychain authentication mode for synchronizing my repository, I get the following error:

index
Transcription: 
**An error occurred during a Git operation**
LifecycleOwner com.zeapo.pwdstore.git.GitServerConfigActivity@f578da1 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

Confirmed with two separate servers (self-hosted Gitea and private Github repo). Tested same two servers/repos with regular SSH keys generated from the app, and these both worked normally.

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Create a container activity to hold the nuts and bolts of our OpenKeychain authentication's `USER_INTERACTION_REQUIRED` stage and employ some sly workarounds to propagate its use.

## :bulb: Motivation and Context
Fixes #1164 

## :green_heart: How did you test it?
Verified I can authenticate using OpenKeychain

## :pencil: Checklist

- [X] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [X] I reviewed submitted code
- [X] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt [hunk 1]
```diff
@@ -33,7 +34,7 @@ import net.schmizz.sshj.userauth.UserAuthException
  * Abstract [AppCompatActivity] that holds some information that is commonly shared across git-related
  * tasks and makes sense to be held here.
  */
-abstract class BaseGitActivity : AppCompatActivity() {
+abstract class BaseGitActivity : ContinuationContainerActivity() {
```
Comment (msfjarvis) [inline app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt:37]: All non-commit operations run through `BaseGitActivity` so it made sense to simply have it extend our container

File: app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt [hunk 2]
```diff
@@ -55,6 +56,7 @@ abstract class GitOperation(protected val callingActivity: FragmentActivity) {
     protected val repository = PasswordRepository.getRepository(null)!!
     protected val git = Git(repository)
     protected val remoteBranch = GitSettings.branch
+    private val authActivity get() = callingActivity as ContinuationContainerActivity
```
Comment (msfjarvis) [inline app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt:59]: `GitOperation` also executes our committing flow which does not invoke authentication related methods, so we get around the overhead of changing every class to extend the container by typecasting at runtime. We've ensured that git operations can only be called from a select few entrypoints which are regulated by us, so this is 'safe'.

**Review by fmeum — APPROVED** [review]
This looks good and is the most direct workaround I can think of.
